## Getting Stated

In [2]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
x = nd.empty((3, 4))
print(x)


[[ 0.0000000e+00  0.0000000e+00 -4.6640310e-35  4.5610864e-41]
 [ 1.3180995e-38  0.0000000e+00  2.9747829e-02  4.5610864e-41]
 [-2.6189484e-39  4.5610864e-41 -2.6202936e-39  4.5610864e-41]]
<NDArray 3x4 @cpu(0)>


In [4]:
x = nd.zeros((3, 5))
x


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<NDArray 3x5 @cpu(0)>

In [5]:
x = nd.ones((3, 4))
x


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [6]:
y = nd.random_normal(0, 1, shape=(3, 4))
y


[[-0.6776515   0.10073948  0.5759544  -0.3469252 ]
 [-0.22134334 -1.804719   -0.8064291   1.220331  ]
 [ 2.2323563   0.2007023  -0.5496865  -0.19819015]]
<NDArray 3x4 @cpu(0)>

In [7]:
y.shape

(3L, 4L)

In [8]:
y.size

12L

## NDArray supports a large number of standard mathematical operations.

In [9]:
print('Additions')
print(x+y)
print('------------------------------------------------------------------------------------')
print('Multiplication')
print(x*y)
print('------------------------------------------------------------------------------------')
print('Exponentiation')
print(nd.exp(y))
print('------------------------------------------------------------------------------------')
print('Dot product')
print(nd.dot(x, y.T))
print('------------------------------------------------------------------------------------')

Additions

[[ 0.32234848  1.1007395   1.5759544   0.6530748 ]
 [ 0.77865666 -0.804719    0.19357091  2.220331  ]
 [ 3.2323563   1.2007023   0.4503135   0.80180985]]
<NDArray 3x4 @cpu(0)>
------------------------------------------------------------------------------------
Multiplication

[[-0.6776515   0.10073948  0.5759544  -0.3469252 ]
 [-0.22134334 -1.804719   -0.8064291   1.220331  ]
 [ 2.2323563   0.2007023  -0.5496865  -0.19819015]]
<NDArray 3x4 @cpu(0)>
------------------------------------------------------------------------------------
Exponentiation

[[0.50780815 1.1059885  1.7788274  0.7068582 ]
 [0.8014415  0.16452068 0.44644946 3.388309  ]
 [9.321805   1.2222608  0.57713073 0.82021385]]
<NDArray 3x4 @cpu(0)>
------------------------------------------------------------------------------------
Dot product

[[-0.34788287 -1.6121604   1.6851819 ]
 [-0.34788287 -1.6121604   1.6851819 ]
 [-0.34788287 -1.6121604   1.6851819 ]]
<NDArray 3x3 @cpu(0)>
---------------------------------

## In-place operations

In [10]:
print('id(y):', id(y))
y = y + x
print('id(y):', id(y))

('id(y):', 139797900293072)
('id(y):', 139797900293328)


In [11]:
print('id(y):', id(y))
y[:] = x + y
print('id(y):', id(y))

('id(y):', 139797900293328)
('id(y):', 139797900293328)


In [12]:
nd.elemwise_add(x, y, out=y)


[[2.3223486 3.1007395 3.5759544 2.6530747]
 [2.7786567 1.195281  2.1935709 4.220331 ]
 [5.232356  3.2007022 2.4503136 2.8018098]]
<NDArray 3x4 @cpu(0)>

In [13]:
print('id(x):', id(x))
x += y
x
print('id(x):', id(x))

('id(x):', 139797913094736)
('id(x):', 139797913094736)


## Slicing

In [14]:
x[1:3]


[[3.7786567 2.195281  3.1935709 5.220331 ]
 [6.232356  4.200702  3.4503136 3.8018098]]
<NDArray 2x4 @cpu(0)>

In [16]:
x[1,2] = 9.0
x


[[3.3223486 4.1007395 4.5759544 3.6530747]
 [3.7786567 2.195281  9.        5.220331 ]
 [6.232356  4.200702  3.4503136 3.8018098]]
<NDArray 3x4 @cpu(0)>